#!/bin/bash

scripts_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
base_dir="$(dirname "$scripts_dir")"
raw_data_dir="$base_dir/raw_data"

declare -a class_names=(
	"age_college"
	"age_mature"
	"age_milf"
	"age_teen"
	"amateur"
	"amateur_self-shots"
	"appearance"
	"appearance_appearance-modification"
	"appearance_appearance-modification_piercings"
	"appearance_appearance-modification_tattoos"
	"appearance_clothing"
	"appearance_clothing_bodyparts-through-clothes"
	"appearance_clothing_bottomless"
	"appearance_clothing_clothed-naked-pair"
	"appearance_clothing_dresses"
	"appearance_clothing_shoes"
	"appearance_clothing_stockings"
	"appearance_clothing_swimwear"
	"appearance_clothing_tight-clothing"
	"appearance_clothing_topless"
	"appearance_clothing_underwear"
	"appearance_clothing_underwear_panties"
	"appearance_clothing_underwear_thongs"
	"appearance_clothing_uniforms-outfits"
	"appearance_clothing_uniforms-outfits_cosplay"
	"appearance_clothing_upskirt-downblouse"
	"appearance_expressions"
	"appearance_pose"
	"appearance_wet-&-messy"
	"artificial-images"
	"artificial-images_fictional-characters-shows"
	"artificial-images_hentai"
	"artificial-images_my-little-pony"
	"artificial-images_photoshop"
	"body-parts_head_hair"
	"body-parts_head_hair_blonde"
	"body-parts_head_hair_brunette"
	"body-parts_head_hair_dyed"
	"body-parts_head_hair_hairstyle"
	"body-parts_head_hair_redhead"
	"body-parts_head_lips-mouth"
	"body-parts_lower-body"
	"body-parts_lower-body_ass"
	"body-parts_lower-body_asshole"
	"body-parts_lower-body_ass_large"
	"body-parts_lower-body_feet"
	"body-parts_lower-body_gap"
	"body-parts_lower-body_genitalia_penis"
	"body-parts_lower-body_genitalia_penis_large"
	"body-parts_lower-body_genitalia_penis_small"
	"body-parts_lower-body_genitalia_vulva"
	"body-parts_lower-body_genitalia_vulva_hair"
	"body-parts_lower-body_genitalia_vulva_labia"
	"body-parts_lower-body_hips"
	"body-parts_lower-body_legs"
	"body-parts_upper-body"
	"body-parts_upper-body_breasts"
	"body-parts_upper-body_breasts_from-an-angle"
	"body-parts_upper-body_breasts_implants"
	"body-parts_upper-body_breasts_large"
	"body-parts_upper-body_breasts_nipples"
	"body-parts_upper-body_breasts_small"
	"body-traits_complexion_freckles"
	"body-traits_complexion_light-skin"
	"body-traits_complexion_tan"
	"body-traits_traits"
	"body-traits_traits_flexible"
	"body-traits_traits_pregnant"
	"body-traits_types_bbw"
	"body-traits_types_chubby"
	"body-traits_types_curvy"
	"body-traits_types_petite"
	"body-traits_types_skinny-thin"
	"classic-vintage"
	"communities"
	"communities_identification"
	"communities_personals"
	"communities_role-play"
	"cum-play_cum"
	"cum-play_cum_creampie"
	"cum-play_cum_cum-shot"
	"cum-play_cum_cum-shot_bukkake"
	"cum-play_cum_cum-shot_facial"
	"cum-play_cum_swallowing"
	"cum-play_female"
	"ethnicity"
	"ethnicity_asian"
	"ethnicity_black"
	"ethnicity_euro"
	"ethnicity_indian"
	"ethnicity_japanese"
	"exhibition"
	"exhibition_gonewild"
	"exhibition_public"
	"fetish"
	"fetish_bdsm"
	"fetish_bdsm_bondage"
	"fetish_bdsm_domination-&-submission"
	"fetish_bdsm_domination-&-submission_femdom"
	"fetish_drugs"
	"fetish_role-enactment"
	"fetish_role-enactment_age-play"
	"fetish_role-enactment_furry"
	"fetish_role-enactment_pet-play"
	"fetish_role-enactment_rape-abuse"
	"fetish_watersports"
	"general-categories"
	"general-categories_artistic-or-borderline-porn"
	"general-categories_desktop-wallpaper"
	"general-categories_gifs"
	"general-categories_humorous"
	"general-categories_p.o.v"
	"general-categories_passionate"
	"general-categories_porn-for-women"
	"general-categories_videos"
	"groups"
	"groups_alt"
	"groups_athlete"
	"groups_camgirl"
	"groups_celebrity"
	"groups_country"
	"groups_nerd"
	"groups_pornstar"
	"groups_pornstar_pornstar-lookalike"
	"groups_religious"
	"groups_specific-personality"
	"illegal-taboo"
	"illegal-taboo_bestiality"
	"illegal-taboo_incest"
	"illegal-taboo_voyeurism"
	"lgbt_bisexual"
	"lgbt_crossdressing"
	"lgbt_gay"
	"lgbt_lesbian"
	"lgbt_transgender"
	"lgbt_transsexual"
	"literary"
	"locations_man-made"
	"locations_nature"
	"locations_nature_beach"
	"non-porn-nsfw"
	"sex"
	"sex_anal"
	"sex_anal_gaping"
	"sex_anal_rimming"
	"sex_breasts"
	"sex_fisting"
	"sex_group"
	"sex_group_large-group"
	"sex_group_swinging"
	"sex_group_threesome"
	"sex_insertion"
	"sex_interracial"
	"sex_masturbation"
	"sex_oral"
	"sex_orgasm"
	"sex_toys"
	"specific-actor-actress"
	"specific-company"
	"wtf"
	)

for cname in "${class_names[@]}"
do
	echo "Getting images for class: $cname"
	urls_file="$raw_data_dir/$cname/urls_$cname.txt"
	while read url
	do
		if [[ ! "$url" =~ ^"#" ]]
		then
			echo "$url"
			java -jar "$scripts_dir/ripme.jar" --skip404 --ripsdirectory "$raw_data_dir/$cname" --url "$url"
		fi
	done < "$scripts_dir/source_urls/$cname.txt"
done

for cname in "${class_names[@]}"
do
	urls_file="$raw_data_dir/$cname/urls_$cname.txt"
	tmpfile=$(mktemp)
	find "$raw_data_dir/$cname" -type f -name "urls.txt" -exec cat {} + >> "$tmpfile"
	grep -e ".jpeg" -e ".jpg" "$tmpfile" > "$urls_file"
	sort -u -o "$urls_file" "$urls_file"
	rm "$tmpfile"
done